---
title: Testing simulations
---

```{r}
set.seed(1234)
library(knitr)
source("../scripts/dynamics_model1.r", local = knitr::knit_global())
```

Define parameters

```{r}
params <- tibble(
    n_id = c(1000),
    scenario = 1,
    time_start = 0,
    time_end = 200,
    time_steps = 1,
    analysis_timepoint = 200,
    per_timepoint = 30,
    per_effect = 0.2,
    disease_threshold = 0.45,
    a = 0.18,
    b = 0.27,
    c = 0.0747,
    e = 0.18,
    f = 0.27,
    g = 0.0585,
    pval_threshold = 1e-4
)

starting_condition_parameters <- tibble(
    scenario = 1,
    n_phen = 3,
    variables = c("X", "K", "P"),
    phen_mean = c(0.74,1.2,1),
    phen_var = c(0.08,0.08,0.08),
    phen_h2 = c(0.2, 0.3, 0.4),
    genotype_af = c(0.2, 0.3, 0.4)
)
```

Run example simulation

```{r}
out <- simulation(params, starting_condition_parameters)
<<<<<<< HEAD

save(out, file = paste0("../results/","sim_data_model1.RData"))
=======
>>>>>>> 4eb3a3ae05592178e7000bfb41e57d78ff150528
```

Distribution of variables at final time point

```{r}
out$dyn %>% 
    subset(time == 200) %>%
    {hist(.$X)}

out$dyn %>% 
    subset(time == 200) %>%
    {hist(.$K)}

out$dyn %>% 
    subset(time == 200) %>%
    {hist(.$P)}
```

Time course of standard dynamics

```{r}
plot_dynamics(out$dyn, out$starting_conditions$phen, 4)
```

Time course of different perturbations

```{r}
plot_dynamics(recreate_data(out$dyn, out$dyn_per$X), out$starting_conditions$phen, 4)
plot_dynamics(recreate_data(out$dyn, out$dyn_per$P), out$starting_conditions$phen, 4)
plot_dynamics(recreate_data(out$dyn, out$dyn_per$K), out$starting_conditions$phen, 4)
```

